import { motion } from "motion/react";
import { Animate, Stagger, StaggerItem, Button } from "../ds";
import { ComponentCard } from "../section-wrapper";
import { RotateCcw, ArrowRight, RefreshCw, ThumbsUp, Share2, Zap } from "lucide-react";
import { AddToCartButton, BookmarkButton, CopyButton, DeleteButton, DownloadButton, LikeButton, NotifyButton, PlusCounter, SendButton, StarRatingButton } from "./microButtons";

type AnimationPreset = "fadeIn" | "fadeInUp" | "fadeInDown" | "fadeInLeft" | "fadeInRight" | "slideUp" | "slideDown" | "slideLeft" | "slideRight" | "scaleIn" | "scaleInBounce" | "rotate" | "flip" | "blur";
type HoverPreset = "pulse" | "shake" | "bounce" | "swing" | "rubberBand";

const mountPresets: AnimationPreset[] = ["fadeIn", "fadeInUp", "fadeInDown", "fadeInLeft", "fadeInRight", "slideUp", "slideDown", "slideLeft", "slideRight", "scaleIn", "scaleInBounce", "rotate", "flip", "blur"];
const hoverPresets: HoverPreset[] = ["pulse", "shake", "bounce", "swing", "rubberBand"];

export function AnimationSectionContent({ mountKey, staggerKey, replay, replayStagger }: { mountKey: number; staggerKey: number; replay: () => void; replayStagger: () => void }) {
  return (
    <>
      <ComponentCard title="Micro-Interactions — Icon Animations in Buttons"><p className="text-[0.75rem] text-muted-foreground mb-4">Click each button to see its icon micro-animation. These patterns are used in DoorDash, Airbnb, and OpenTable-style apps.</p><div className="flex flex-wrap gap-3"><LikeButton /><BookmarkButton /><AddToCartButton /><SendButton /><NotifyButton /><DeleteButton /><DownloadButton /><CopyButton /></div></ComponentCard>
      <ComponentCard title="Interactive Star Rating"><p className="text-[0.75rem] text-muted-foreground mb-3">Click stars — each animates with a cascade</p><StarRatingButton /></ComponentCard>
      <ComponentCard title="Animated Counter"><p className="text-[0.75rem] text-muted-foreground mb-3">Tap the + button — icon rotates and counter slides in</p><PlusCounter /></ComponentCard>
      <ComponentCard title="Button Hover Icon Effects"><p className="text-[0.75rem] text-muted-foreground mb-4">Hover to see icons animate</p><div className="flex flex-wrap gap-3"><motion.button whileHover="hovered" className="inline-flex items-center gap-2 px-4 py-2.5 rounded-lg bg-primary text-primary-foreground hover:opacity-90 cursor-pointer text-[0.8125rem]">Explore<motion.span variants={{ hovered: { x: 5 } }} transition={{ type: "spring", stiffness: 300 }}><ArrowRight className="w-4 h-4" /></motion.span></motion.button><motion.button whileHover="hovered" className="inline-flex items-center gap-2 px-4 py-2.5 rounded-lg border border-border hover:bg-secondary cursor-pointer text-[0.8125rem]"><motion.span variants={{ hovered: { rotate: 180 } }} transition={{ duration: 0.4 }}><RefreshCw className="w-4 h-4" /></motion.span>Refresh</motion.button><motion.button whileHover="hovered" className="inline-flex items-center gap-2 px-4 py-2.5 rounded-lg border border-border hover:bg-secondary cursor-pointer text-[0.8125rem]"><motion.span variants={{ hovered: { y: -3, scale: 1.15 } }} transition={{ type: "spring" }}><ThumbsUp className="w-4 h-4" /></motion.span>Upvote</motion.button><motion.button whileHover="hovered" className="inline-flex items-center gap-2 px-4 py-2.5 rounded-lg border border-border hover:bg-secondary cursor-pointer text-[0.8125rem]">Share<motion.span variants={{ hovered: { rotate: 15, scale: 1.2 } }} transition={{ type: "spring" }}><Share2 className="w-4 h-4" /></motion.span></motion.button><motion.button whileHover="hovered" className="inline-flex items-center gap-2 px-4 py-2.5 rounded-lg bg-warning text-warning-foreground hover:opacity-90 cursor-pointer text-[0.8125rem]"><motion.span variants={{ hovered: { scale: [1, 1.3, 1], rotate: [0, -10, 10, 0] } }} transition={{ duration: 0.5 }}><Zap className="w-4 h-4" /></motion.span>Boost</motion.button></div></ComponentCard>
      <ComponentCard title="Mount Animations"><div className="flex items-center gap-3 mb-4"><Button variant="outline" size="sm" leftIcon={<RotateCcw className="w-3.5 h-3.5" />} onClick={replay}>Replay All</Button><span className="text-[0.75rem] text-muted-foreground">Click to replay mount animations</span></div><div key={mountKey} className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-3">{mountPresets.map((preset, i) => <Animate key={preset} preset={preset} delay={i * 0.06} duration={0.5}><div className="p-4 rounded-xl border border-border bg-card text-center"><div className="w-10 h-10 rounded-lg bg-primary/15 text-primary flex items-center justify-center mx-auto mb-2"><span className="text-[1rem]">?</span></div><p className="text-[0.6875rem] font-mono text-muted-foreground">{preset}</p></div></Animate>)}</div></ComponentCard>
      <ComponentCard title="Hover Animations"><p className="text-[0.75rem] text-muted-foreground mb-4">Hover over each card to see the animation</p><div className="flex flex-wrap gap-3">{hoverPresets.map((preset) => <Animate key={preset} preset={preset} trigger="hover"><div className="px-5 py-4 rounded-xl border border-border bg-card text-center cursor-pointer hover:border-primary/30 transition-colors"><div className="w-8 h-8 rounded-full bg-primary/15 text-primary flex items-center justify-center mx-auto mb-2"><span className="text-[0.875rem]">?</span></div><p className="text-[0.6875rem] font-mono text-muted-foreground">{preset}</p></div></Animate>)}</div></ComponentCard>
      <ComponentCard title="In-View Animations"><p className="text-[0.75rem] text-muted-foreground mb-4">Scroll to see these appear (trigger="inView")</p><div className="grid grid-cols-1 sm:grid-cols-3 gap-4">{(["fadeInUp", "scaleIn", "fadeInRight"] as const).map((preset, i) => <Animate key={preset} preset={preset} trigger="inView" delay={i * 0.15} duration={0.6}><div className="p-6 rounded-xl border border-border bg-card"><h4 className="text-[0.9375rem] mb-1">{preset}</h4><p className="text-[0.8125rem] text-muted-foreground">This card animates when scrolled into view.</p></div></Animate>)}</div></ComponentCard>
      <ComponentCard title="Stagger Animation"><div className="flex items-center gap-3 mb-4"><Button variant="outline" size="sm" leftIcon={<RotateCcw className="w-3.5 h-3.5" />} onClick={replayStagger}>Replay Stagger</Button></div><Stagger key={staggerKey} stagger={0.08} delayStart={0.1}><div className="grid grid-cols-2 sm:grid-cols-4 gap-3">{Array.from({ length: 8 }, (_, i) => <StaggerItem key={i} preset="fadeInUp"><div className="p-4 rounded-xl border border-border bg-card text-center"><div className="w-full h-20 rounded-lg mb-2" style={{ background: `hsl(${(i * 45) % 360}, 70%, 90%)` }} /><p className="text-[0.75rem] text-muted-foreground">Item {i + 1}</p></div></StaggerItem>)}</div></Stagger></ComponentCard>
    </>
  );
}
