const INTERNAL_BALANCE_KRW = 13_000_000;
const BONUS_BALANCE_KRW = 330_000;
const WALLET_BALANCE_USD = 5000.0;
const USD_TO_KRW = 1350;
const POINTS_EARN_RATE = 2;

export { INTERNAL_BALANCE_KRW, BONUS_BALANCE_KRW, WALLET_BALANCE_USD, USD_TO_KRW, POINTS_EARN_RATE };
