import type { NewsItem } from "./types";

export const MOCK_NEWS: NewsItem[] = [
  {
    id: "n-101",
    category: "Award",
    title: "Three Bay Area Restaurants Earn Their First Michelin Star",
    summary: "The 2026 Michelin Guide spotlights bold new voices in California fine dining.",
    body: "The 2026 California Michelin Guide unveiled today recognizes three first-time stars across the Bay Area. Inspectors highlighted impeccable seasonal sourcing, technically refined plating and a renewed focus on hospitality. Reservations have already surged 480% in the first 12 hours after the announcement, with most restaurants booked solid through the next eight weeks.",
    image: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=800&h=600&fit=crop",
    author: "Maya Tanaka",
    authorAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop",
    publishedAt: new Date(Date.now() - 1000 * 60 * 42).toISOString(),
    readMinutes: 4,
    tags: ["Michelin", "Fine Dining", "Bay Area"],
  },
  {
    id: "n-102",
    category: "New Opening",
    title: "Chef Daniel Park Opens Hansik Tasting Counter in Hayes Valley",
    summary: "A 12-seat omakase-style Korean counter brings rare regional dishes to the city.",
    body: "After three years cooking in Seoul and Busan, chef Daniel Park returns with Hansik Counter — a 12-seat tasting room dedicated to lesser-known regional Korean cooking. The 14-course menu draws on hand-foraged seaweeds, slow-aged kimchi, and a brassware-only service tradition. Booking opens Friday at 10 AM and is expected to fill quickly.",
    image: "https://images.unsplash.com/photo-1590189599125-67138c6509ef?w=800&h=600&fit=crop",
    author: "Jin Lee",
    authorAvatar: "https://images.unsplash.com/photo-1502685104226-ee32379fefbe?w=100&h=100&fit=crop",
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    readMinutes: 3,
    tags: ["Opening", "Korean", "Tasting Menu"],
  },
  {
    id: "n-103",
    category: "Trending",
    title: "Why Everyone Is Suddenly Obsessed with Hand-Pulled Knife Noodles",
    summary: "The texture-forward dish is breaking out of regional menus and into the mainstream.",
    body: "From Flushing to Oakland, knife-cut and hand-pulled noodles are dominating social feeds — and reservation queues. Chefs cite a renewed appetite for craft and visible technique post-pandemic. We round up six counters where the dough hits the table within minutes of being shaped.",
    image: "https://images.unsplash.com/photo-1731460202531-bf8389d565f7?w=800&h=600&fit=crop",
    author: "Renee Cho",
    authorAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&h=100&fit=crop",
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 22).toISOString(),
    readMinutes: 5,
    tags: ["Trending", "Noodles", "Asian"],
  },
  {
    id: "n-104",
    category: "Event",
    title: "Spring Truffle Week Returns with 38 Participating Restaurants",
    summary: "April 28 – May 5: prix-fixe truffle menus from $65 across the city.",
    body: "Spring Truffle Week kicks off next Monday with a record 38 participating restaurants. Diners can book curated three-course menus starting at $65, and the festival pass unlocks priority seating at flagship Italian, French, and modern American kitchens.",
    image: "https://images.unsplash.com/photo-1681270507609-e2a5f21969b0?w=800&h=600&fit=crop",
    author: "Marco Bellini",
    authorAvatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=100&h=100&fit=crop",
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 30).toISOString(),
    readMinutes: 2,
    tags: ["Event", "Truffle", "Festival"],
  },
  {
    id: "n-105",
    category: "Chef",
    title: "Pastry Chef Aiko Sato Wins National Dessert of the Year",
    summary: "Her yuzu-pine ice cream sweeps the judges at the 2026 Pastry Awards.",
    body: "Aiko Sato of Patisserie Ume took home the National Dessert of the Year for her yuzu-pine ice cream — a dish nine months in development. Judges praised the layered aromatics and balance of acidity. Tasting menu seats featuring the dish are released every Sunday at midnight.",
    image: "https://images.unsplash.com/photo-1657502996869-6ccd568b9d41?w=800&h=600&fit=crop",
    author: "Hannah Wright",
    authorAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop",
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    readMinutes: 3,
    tags: ["Pastry", "Award", "Dessert"],
  },
  {
    id: "n-106",
    category: "Guide",
    title: "12 Patios Worth Booking Before Summer Hits",
    summary: "Our updated 2026 patio guide ranks the best al fresco dining in the city.",
    body: "We walked, dined and lingered through every notable patio in town. The 2026 list balances skyline views, tree-lined courtyards and sea-breeze terraces. Each pick links to live availability so you can book your table before the crowds arrive.",
    image: "https://images.unsplash.com/photo-1598990386084-8af4dd12b3b4?w=800&h=600&fit=crop",
    author: "Chris Donovan",
    authorAvatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&h=100&fit=crop",
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    readMinutes: 6,
    tags: ["Guide", "Outdoor", "Summer"],
  },
];
