import { ArrowLeft, Clock3, MessageCircle, Play, Volume2 } from "lucide-react";
import { Button } from "../../../../components/ds/Button";
import { Card } from "../../../../components/ds/Card";
import { Text } from "../../../../components/ds/Text";
import { ImageWithFallback } from "../../../../components/figma/ImageWithFallback";
import { SectionHelpfulness } from "../HelpCenterPrimitives";
import type { Section } from "../types";
import { SectionLabel } from "./shared";

export function HelpTopicView({ activeTopic, sections, onJump, onSpeak, onFeedback, onGoIndex, onContactSupport }: { activeTopic: Section; sections: Section[]; onJump: (id: string) => void; onSpeak: (text: string) => void; onFeedback: (id: string, value: "up" | "down") => void; onGoIndex: () => void; onContactSupport?: () => void }) {
  return (
    <div className="space-y-5">
      <section id={`help-${activeTopic.id}`} className="scroll-mt-4"><div className="relative overflow-hidden rounded-[1.75rem] border border-border bg-card shadow-[0_8px_24px_rgba(0,0,0,0.08)]"><div className="relative h-[11rem] sm:h-[13rem]"><ImageWithFallback src={activeTopic.image} alt={activeTopic.title} className="h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-black/75 via-black/20 to-black/5" /><div className="absolute inset-x-0 bottom-0 p-4"><div className="flex flex-wrap items-center gap-2"><span className="inline-flex items-center gap-1 rounded-full bg-white px-2.5 py-1 text-[0.6875rem] text-primary shadow-sm" style={{ fontWeight: 800 }}><activeTopic.icon className="h-3.5 w-3.5" />{activeTopic.title}</span><span className="inline-flex items-center gap-1 rounded-full bg-black/50 px-2.5 py-1 text-[0.6875rem] text-white"><Clock3 className="h-3 w-3" />{activeTopic.readMins} min</span>{activeTopic.video && <span className="inline-flex items-center gap-1 rounded-full bg-black/50 px-2.5 py-1 text-[0.6875rem] text-white"><Play className="h-3 w-3" />{activeTopic.video.length}</span>}</div><h2 className="mt-2 text-[1.45rem] leading-tight text-white sm:text-[1.625rem]" style={{ fontWeight: 800 }}>{activeTopic.title}</h2><Text className="mt-1 line-clamp-2 text-[0.8125rem] leading-snug text-white/85">{activeTopic.summary}</Text></div><button type="button" onClick={() => onSpeak(`${activeTopic.title}. ${activeTopic.summary}`)} className="absolute right-3 top-3 flex h-10 w-10 cursor-pointer items-center justify-center rounded-full bg-white/90 text-foreground shadow-sm transition hover:bg-white active:scale-95" aria-label="Read aloud" title="Read aloud"><Volume2 className="h-4.5 w-4.5" /></button></div></div>
        <Card variant="default" padding="md" radius="xl" className="mt-4 shadow-[0_3px_16px_rgba(0,0,0,0.04)]">{activeTopic.render(onJump)}{activeTopic.video && <div className="mt-5 flex items-center gap-3 rounded-[1.25rem] border border-border bg-secondary/45 p-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-primary/10 text-primary"><Play className="h-4 w-4" /></span><span className="min-w-0 flex-1"><Text className="truncate text-[0.875rem]" style={{ fontWeight: 700 }}>{activeTopic.video.title}</Text><Text className="text-[0.75rem] text-muted-foreground">Video walkthrough - {activeTopic.video.length}</Text></span><Button variant="outline" size="sm" radius="full" className="shrink-0">Watch</Button></div>}{activeTopic.related.length > 0 && <div className="mt-5"><SectionLabel>Related</SectionLabel><div className="flex flex-wrap gap-2">{activeTopic.related.map((relatedId) => { const related = sections.find((section) => section.id === relatedId); if (!related) return null; return <button key={relatedId} type="button" onClick={() => onJump(relatedId)} className="inline-flex h-9 cursor-pointer items-center gap-1.5 rounded-full bg-primary/10 px-3 text-[0.8125rem] text-primary transition hover:bg-primary/15 active:scale-95" style={{ fontWeight: 700 }}><related.icon className="h-3.5 w-3.5" />{related.title}</button>; })}</div></div>}<SectionHelpfulness sectionId={activeTopic.id} onFeedback={onFeedback} /></Card></section>
      <div className="flex items-center justify-between gap-3 pt-1"><Button variant="outline" radius="full" leftIcon={<ArrowLeft className="h-4 w-4" />} onClick={onGoIndex} className="min-h-11">All topics</Button><Button variant="primary" radius="full" leftIcon={<MessageCircle className="h-4 w-4" />} onClick={() => onContactSupport?.()} className="min-h-11">Contact</Button></div>
    </div>
  );
}
